bytecodealliance/wasi-rs

Cargo.toml
It will allow `wasi` to be used as a `libstd` dependency. See this [comment](https://github.com/rust-lang/rust/pull/62082#issuecomment-521399966).
=> Add rustc-dep-of-std feature

crates/generate-raw/src/lib.rs, src/lib.rs
Following @RalfJung's comment here:
https://github.com/bytecodealliance/wasi/issues/8#issuecomment-525711768
as long as the functions are still taking integer file descriptor
arguments, we should mark the APIs here `unsafe`.
This is particularly interesting in the context of WASI, as it aligns with
the OCap security model -- Rust's `std::fs::File` is an unforgeable
handle in safe Rust. So while there are still integer file descriptors at
the wasm level for now, programs compiled from safe Rust still have
fine-grained isolation (with the caveat that until reference types are
possible, this property isn't encoded in wasm in a verifiable way).
=> Mark the highlevel functions as unsafe.

Cargo.toml, src/lib.rs
Cargo was interpreting the old comment as a doc test; reformat it so
that it doesn't.
=> Bump to 0.9.0 and fix comment syntax.

crates/generate-raw/src/lib.rs
For the moment, a handle just consists of an opaque u32 value.
Tested by rendering the ephemeral version of WASI, which uses handle
for file descriptors.
=> Support rendering the "handle" witx type, as a u32 for now

src/lib.rs
=> Provide DIRCOOKIE_START, FD_STDIN, FD_STDOUT, and FD_STDERR.

crates/generate-raw/Cargo.toml, crates/generate-raw/src/lib.rs, crates/generate-raw/src/main.rs, crates/generate-raw/tests/verify.rs, crates/wasi-ephemeral/Cargo.toml, crates/wasi-ephemeral/build.rs, src/lib_generated.rs
This commit fast-forwards the `WASI` submodule and updates the
relevant the machinery. It also updates `generate_raw::generate`
fn to accept a slice in preparation for multi-module `wasi_ephemeral`.
Changes introduced by this PR:
* change signature of `generate_raw::generate` from `fn generate(&Path)` to `fn <P: AsRef<Path>>generate(&[P])`; this effectively is needed if we want to be able to generate bindings from multi-module snapshots such as `ephemeral`.
* add feature `multi-module` to `generate` crate which serves as a workaround for avoiding name clashes for syscalls that are a very present danger introduced in multi-module `ephemeral` snapshot; this "hack", when the feature is enabled, prepends the Wasm module name to the syscall's name when generating Rust wrappers. This is a …
=> FF WASI submodule and update the machinery

crates/generate-raw/src/lib.rs
This follows directly from the discussion in #42 where we agreed
that `char8` is essentially a named "alias" to a byte type (`u8`)
and represents a code *unit* (much like `char8_t` in C++20), rather
than a code *point* (as is the case with multi-byte type `char` in
Rust).
=> Change repr of char8 from char to u8

crates/generate-raw/src/lib.rs, src/lib_generated.rs
DO NOT MERGE until upstream WASI changes are merged into master, and submodule is pointed at master.
Implements https://github.com/WebAssembly/WASI/pull/220/
=> update to use tagged unions

crates/generate-raw/src/lib.rs, src/lib_generated.rs
=> Add `derive(Debug)` to generated struct types.

.github/workflows/main.yml
This should fix errors like those observed in https://github.com/bytecodealliance/wasi/pull/46/checks?check_run_id=1009925040#step:9:99.
=> ci: install rustfmt (used by generate-raw crate)

crates/witx-bindgen/README.md, crates/witx-bindgen/src/main.rs, crates/witx-bindgen/tests/verify.rs
Previously, the witx path was hard-coded to a snapshot but this change allows me to use it for wasi-nn.
=> Allow generate-raw to run single witx files

crates/witx-bindgen/src/lib.rs
This prints out more details about the offending parameter.
=> Make unimplemented error more clear

crates/witx-bindgen/src/lib.rs, src/lib_generated.rs
This PR makes tiny improvement for the generated `src/lib_generated.rs` from witx.
Currently generated code lacks explicit lifetime parameter when an aliased type is referred as an argument, which is [encouraged to put explicitly in Rust 2018](https://doc.rust-lang.org/edition-guide/rust-2018/ownership-and-lifetimes/the-anonymous-lifetime.html#more-details).
In fact these optional warnings prevents me from compiling rust-lang/rust with pointing `wasi` dependency to my local copy by following errors.
```
error: hidden lifetime parameters in types are deprecated
--> /Users/masked/wasi/src/lib_generated.rs:958:38
|
958 | pub unsafe fn fd_pread(fd: Fd, iovs: IovecArray, offset: Filesize) -> Result<Size> {
|                                      ^^^^^^^^^^- help: indicate the anonymous …
```
=> Generate lifetime parameter explicitly for aliased PointerLengthPair

crates/witx-bindgen/Cargo.toml
Disclaimer: this is a via-github en-passant PR, nothing is actually tested but hopefully it'll add the repository link to crates.io so other people don't have to also use the github search to figure out where the source code lives.
=> Add the repository so people know where to look for the source code

Cargo.toml, src/lib_generated.rs
The most notable change here is the addition of the `sock_accept()` call.
https://github.com/WebAssembly/WASI/pull/458
=> Update to the latest WASI snapshot1 and release 0.10.3

ci/regenerate.sh, src/bindings.rs
This will help prevent clashes with any other world called "bindings" by ensuring that wasm-ld doesn't concatenate sections and corrupt the internal contents.
=> Add a suffix to the metadata section for component types

.github/workflows/main.yml
Avoid minor patch updates for versions of dependencies to ensure that the output stays consistent over time for CI checks.
=> Use `--locked` when installing `wit-bindgen-cli`

ci/rustfmt-bindings.toml
As of #81, this rustfmt-bindings.toml file is no longer used.
=> Delete unused rustfmt-bindings.toml file.

.github/workflows/main.yml, README.md, src/lib.rs
Update CI and a few strings of documentation here and there.
=> Rename `wasm32-wasi` to `wasm32-wasip1`

src/lib.rs
Add the closing side of HTML comments, to fix cargo doc warnings.
=> Fix cargo doc warnings about HTML comments.

README.md
Update the documentation to prominently describe the new wasm32-wasip2 target, to mention cargo component, and to put the existing wasm32-wasip1 with adapter approach in context.
=> Document the now three ways to use the wasi crate.

Cargo.toml
Bump to 0.14.0+wasi-0.2.3, from 0.13.4+wasi-0.2.3, as the update to wit-bindgen 0.37 includes some minor semver incompatibilies.
=> Bump to 0.14.0+wasi-0.2.3

Cargo.toml
Publish a new version with the dependency on `wasip2`
=> Bump to 0.14.5
